[build]
  publish = "dist"
  command = "npm run build"

# Specific rule for Amazon OAuth callback
[[redirects]]
  from = "/api/amazon-callback"
  to = "/index.html"
  status = 200
  force = true

# Handle OPTIONS preflight requests for CORS - this must come first
[[redirects]]
  from = "/api/supabase/*"
  to = "https://wllhsxoabzdzulomizzx.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH", Access-Control-Allow-Headers = "*", Access-Control-Max-Age = "86400"}
  methods = ["OPTIONS"]

# CORS Proxy for Supabase Functions - this comes after OPTIONS
[[redirects]]
  from = "/api/supabase/*"
  to = "https://wllhsxoabzdzulomizzx.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH", Access-Control-Allow-Headers = "*", Access-Control-Allow-Credentials = "true"}

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200