[build]
  publish = "dist"
  command = "npm run build"

# Specific rule for Amazon OAuth callback
[[redirects]]
  from = "/api/amazon-callback"
  to = "/index.html"
  status = 200
  force = true

# CORS Proxy for Supabase Functions
[[redirects]]
  from = "/api/supabase/*"
  to = "https://wllhsxoabzdzulomizzx.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, apikey, x-client-info"}

# Handle OPTIONS preflight requests for CORS
[[redirects]]
  from = "/api/supabase/*"
  to = "https://wllhsxoabzdzulomizzx.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "*", Access-Control-Max-Age = "86400"}
  methods = ["OPTIONS"]

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200