// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wllhsxoabzdzulomizzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbGhzeG9hYnpkenVsb21penp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjcxMTQsImV4cCI6MjA1NTk0MzExNH0.grR0m4oXBigY-o9dsvdw6l4zy2DPoneSzWyvhQSZsWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);